import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navbar
    'nav.home': 'Главная',
    'nav.portfolio': 'Портфолио',
    'nav.pricing': 'Услуги',
    'nav.about': 'Обо мне',
    'nav.discuss': 'Обсудить проект',
    
    // Footer
    'footer.desc': 'Премиальная веб-разработка и дизайн.',
    
    // Home
    'home.available': 'Доступен для новых проектов',
    'home.title1': 'Создаю сайты, которые',
    'home.title2': 'продают дорого',
    'home.desc': 'Премиальная веб-разработка и дизайн для бизнеса, который хочет выделяться. От лендингов до сложных корпоративных порталов.',
    'home.viewWork': 'Смотреть работы',
    'home.services': 'Услуги и цены',
    'home.whyMe': 'Почему выбирают меня',
    'home.quality.title': 'Студийное качество',
    'home.quality.desc': 'Вы получаете уровень топового digital-агентства, работая напрямую с исполнителем без переплат за менеджмент.',
    'home.conversion.title': 'Конверсия в основе',
    'home.conversion.desc': 'Каждый пиксель и анимация работают на удержание внимания и подведение пользователя к целевому действию.',
    'home.stack.title': 'Современный стек',
    'home.stack.desc': 'Использую React, Tailwind, Framer Motion для создания быстрых, плавных и надежных интерфейсов.',
    'home.testimonials': 'Что говорят клиенты',
    'home.testimonial1.text': 'Работа превзошла все ожидания. Сайт выглядит невероятно дорого, анимации плавные, конверсия выросла на 40% в первый месяц.',
    'home.testimonial1.author': 'Александр В.',
    'home.testimonial1.role': 'CEO TechStartup',
    'home.testimonial2.text': 'Искали премиальный дизайн для нашего бренда. Получили шедевр. Очень комфортная коммуникация и соблюдение всех сроков.',
    'home.testimonial2.author': 'Елена М.',
    'home.testimonial2.role': 'Основатель Beauty Studio',
    'home.cta.title1': 'Готовы создать',
    'home.cta.title2': 'нечто выдающееся?',
    'home.cta.desc': 'Оставьте заявку, и мы обсудим ваш проект, цели и то, как дизайн может помочь вашему бизнесу расти.',
    'home.cta.btn': 'Связаться со мной',
    
    // Portfolio
    'portfolio.title1': 'Мои',
    'portfolio.title2': 'работы',
    'portfolio.desc': 'Проекты, которыми я горжусь. От концепции до финального пикселя.',
    'portfolio.services1': 'услуги, которые я предоставляю',
    'portfolio.services2': 'для вашего бизнеса',
    'portfolio.consultation': 'Консультация',
    'portfolio.startProject': 'Начать проект',
    'portfolio.hero.desc': 'Мы — команда экспертов в области дизайна, помогающая бизнесу расти через визуальную идентичность.',
    'portfolio.stats.budget.title': '$60k+',
    'portfolio.stats.budget.desc': 'мы управляем рекламным бюджетом каждый месяц',
    'portfolio.stats.posts.title': '1.3k+',
    'portfolio.stats.posts.desc': 'мы создаем уникальные посты и креативы каждый месяц для растущих брендов',
    'portfolio.transform.title1': 'мы превращаем',
    'portfolio.transform.title2': 'подписчиков',
    'portfolio.transform.title3': 'в клиентов',
    'portfolio.transform.desc': 'Наш подход основан на аналитике, креативности и эффективных маркетинговых стратегиях.',
    'portfolio.nextgen.title1': 'мы —',
    'portfolio.nextgen.title2': 'next-gen',
    'portfolio.nextgen.title3': 'дизайн-агентство',
    'portfolio.services.uiux.title': 'UI/UX\nДизайн',
    'portfolio.services.uiux.desc': 'Исследования пользователей, вайрфрейминг, прототипирование и дизайн интерфейсов высокой точности.',
    'portfolio.services.brand.title': 'Бренд\nАйдентика',
    'portfolio.services.brand.desc': 'Дизайн логотипов, брендбуки, типографика и визуальный язык.',
    'portfolio.services.web.title': 'Веб\nРазработка',
    'portfolio.services.web.desc': 'Фронтенд-разработка, анимации, адаптивный дизайн и интеграция CMS.',
    'portfolio.services.motion.title': 'Моушн\nДизайн',
    'portfolio.services.motion.desc': '2D/3D анимации, промо-ролики и интерактивные веб-элементы.',
    'portfolio.data.title1': 'данные, которые',
    'portfolio.data.title2': 'доказывают',
    'portfolio.data.title3': 'наше влияние',
    'portfolio.data.card1.title': 'Наши ключевые результаты',
    'portfolio.data.card1.desc': 'Целевые дизайн-кампании, которые достигают нужной аудитории в нужное время.',
    'portfolio.data.card1.stat1': 'лучше конверсия',
    'portfolio.data.card1.stat2': 'улучшение ROI',
    'portfolio.data.card2.title': 'Бюджет в 2024',
    'portfolio.data.card2.desc': 'Стратегически распределен для охвата целевой аудитории и стимулирования конверсий.',
    'portfolio.data.card3.title': 'Удовлетворенность',
    'portfolio.data.card3.desc': 'На основе опросов после завершения проектов среди всех наших корпоративных клиентов.',
    'portfolio.data.card4.title': 'Реализовано проектов',
    'portfolio.data.card4.desc': 'Успешно запущенные цифровые продукты, бренды и маркетинговые кампании.',
    'portfolio.data.card5.title': 'Глобальный охват',
    'portfolio.data.card5.desc': 'Работаем с клиентами и партнерами на разных континентах и в разных часовых поясах.',
    'portfolio.data.card6.title': 'Получено наград',
    'portfolio.data.card6.desc': 'Признание от Awwwards, CSS Design Awards и других лидеров индустрии.',
    'portfolio.who.title1': 'для кого',
    'portfolio.who.title2': 'наши услуги',
    'portfolio.who.subtitle': '/ идеальное решение',
    'portfolio.who.card1': 'Малый и средний бизнес',
    'portfolio.who.card2.desc': 'Высокоуровневая таргетированная реклама привлекает студентов и клиентов, ищущих профессиональное образование или консалтинг, увеличивая количество регистраций и запросов.',
    'portfolio.who.card2.title': 'Образовательные и консалтинговые услуги',
    'portfolio.who.card3': 'Маркетинговые агентства',
    'portfolio.who.card4': 'E-commerce',
    'portfolio.who.card5': 'Корпоративные клиенты',
    'portfolio.who.card6': 'Стартапы',
    'portfolio.work.title1': 'наша работа',
    'portfolio.work.title2': 'говорит',
    'portfolio.work.title3': 'за нас',
    'portfolio.creatives.title1': 'креативы,',
    'portfolio.creatives.title2': 'которые',
    'portfolio.creatives.title3': 'работают',
    'portfolio.creatives.title4': 'на вас',
    
    // Portfolio Projects
    'portfolio.projects.1.title': 'Запуск Instagram-аккаунта для студии красоты с нуля.',
    'portfolio.projects.1.desc': '3 100 подписчиков за первые 2 недели, запись на 2 недели вперед.',
    'portfolio.projects.2.title': 'Ребрендинг и веб-дизайн для локальной кофейни.',
    'portfolio.projects.2.desc': 'Увеличение посещаемости на 40% и онлайн-заказов на 150%.',
    'portfolio.projects.3.title': 'E-commerce платформа для модного бутика.',
    'portfolio.projects.3.desc': 'Оптимизация конверсии, приведшая к ежемесячной выручке более $100k.',
    'portfolio.projects.4.title': 'UI/UX дизайн фитнес-приложения и исследование пользователей.',
    'portfolio.projects.4.desc': 'Более 10k скачиваний в первый месяц с рейтингом 4.9 звезды.',
    'portfolio.projects.5.title': 'Корпоративная айдентика для технологического стартапа.',
    'portfolio.projects.5.desc': 'Привлечено $2M посевных инвестиций с новым питч-деком и брендингом.',

    // Portfolio Services List
    'portfolio.servicesList.category': 'Услуга',
    'portfolio.servicesList.1.title': 'Дизайн',
    'portfolio.servicesList.2.title': 'Веб Дизайн',
    'portfolio.servicesList.3.title': 'Моушн Дизайн',
    'portfolio.servicesList.4.title': 'UI Дизайн',
    'portfolio.servicesList.5.title': 'Корпоративный Дизайн',
    'portfolio.servicesList.6.title': 'Другое',
    
    // Pricing
    'pricing.title1': 'Прозрачные',
    'pricing.title2': 'цены',
    'pricing.desc': 'Выберите подходящий формат сотрудничества. Без скрытых платежей и сюрпризов.',
    'pricing.landing': 'Лендинг',
    'pricing.landing.price': 'от ₽10000',
    'pricing.landing.desc': 'Идеально для запуска продукта, мероприятия или сбора лидов.',
    'pricing.landing.f1': 'Уникальный премиум-дизайн',
    'pricing.landing.f2': 'Адаптивная верстка (React/Tailwind)',
    'pricing.landing.f3': 'Базовые анимации (Framer Motion)',
    'pricing.landing.f4': 'Интеграция форм заявки',
    'pricing.landing.f5': 'Базовая SEO-оптимизация',
    'pricing.corp': 'Корпоративный сайт',
    'pricing.corp.price': 'от ₽15000',
    'pricing.corp.desc': 'Многостраничный сайт для полноценного представления компании.',
    'pricing.corp.f1': 'До 10 уникальных страниц',
    'pricing.corp.f2': 'Сложные интерактивные элементы',
    'pricing.corp.f3': 'CMS для управления контентом',
    'pricing.corp.f4': 'Продвинутые анимации',
    'pricing.corp.f5': 'Оптимизация скорости загрузки',
    'pricing.corp.f6': 'Поддержка 1 месяц',
    'pricing.front': 'Frontend Разработка',
    'pricing.front.price': '₽2000/час',
    'pricing.front.desc': 'Реализация вашего готового дизайна на современном стеке.',
    'pricing.front.f1': 'Pixel-perfect верстка',
    'pricing.front.f2': 'React / Next.js / Vue',
    'pricing.front.f3': 'Сложные WebGL/Canvas эффекты',
    'pricing.front.f4': 'Интеграция с API',
    'pricing.front.f5': 'Рефакторинг старого кода',
    'pricing.popular': 'Популярный выбор',
    'pricing.order': 'Заказать',
    
    // About
    'about.title1': 'Давайте',
    'about.title2': 'знакомиться',
    'about.desc1': 'Я — frontend-разработчик и дизайнер интерфейсов с фокусом на премиальный визуальный опыт. Моя цель — не просто написать код, а создать продукт, который вызывает эмоции и приносит прибыль.',
    'about.desc2': 'В своей работе я объединяю строгую инженерную логику с креативным подходом. Я верю, что хороший дизайн должен быть не только красивым, но и функциональным, быстрым и доступным.',
    'about.process.title': 'Мой процесс',
    'about.process.1.title': 'Брифинг и аналитика',
    'about.process.1.desc': 'Погружаюсь в ваш бизнес, изучаю аудиторию и конкурентов.',
    'about.process.2.title': 'Концепт и дизайн',
    'about.process.2.desc': 'Создаю визуальную систему, прототипы и премиальный UI.',
    'about.process.3.title': 'Разработка и анимации',
    'about.process.3.desc': 'Верстаю pixel-perfect, добавляю плавные motion-эффекты.',
    'about.process.4.title': 'Запуск и поддержка',
    'about.process.4.desc': 'Тестирую, оптимизирую и помогаю с развитием проекта.',
    'about.contact.tg': 'Написать в Telegram',
    'about.form.title': 'Оставить заявку',
    'about.form.desc': 'Расскажите вкратце о вашей задаче, и я свяжусь с вами в течение дня для обсуждения деталей.',
    'about.form.nameLabel': 'Ваше имя',
    'about.form.namePlaceholder': 'Иван Иванов',
    'about.form.contactLabel': 'Email или Telegram',
    'about.form.contactPlaceholder': '@username или email@domain.com',
    'about.form.projectLabel': 'О проекте',
    'about.form.projectPlaceholder': 'Какая задача стоит перед вами?',
    'about.form.submit': 'Отправить',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.portfolio': 'Portfolio',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.discuss': 'Discuss Project',
    
    // Footer
    'footer.desc': 'Premium web development and design.',
    
    // Home
    'home.available': 'Available for new projects',
    'home.title1': 'I build websites that',
    'home.title2': 'sell at a premium',
    'home.desc': 'Premium web development and design for businesses that want to stand out. From landing pages to complex corporate portals.',
    'home.viewWork': 'View Portfolio',
    'home.services': 'Services & Pricing',
    'home.whyMe': 'Why choose me',
    'home.quality.title': 'Studio Quality',
    'home.quality.desc': 'You get top digital agency level, working directly with the developer without management markups.',
    'home.conversion.title': 'Conversion at the Core',
    'home.conversion.desc': 'Every pixel and animation works to retain attention and guide the user to the target action.',
    'home.stack.title': 'Modern Stack',
    'home.stack.desc': 'I use React, Tailwind, and Framer Motion to create fast, smooth, and reliable interfaces.',
    'home.testimonials': 'What clients say',
    'home.testimonial1.text': 'The work exceeded all expectations. The site looks incredibly expensive, animations are smooth, conversion increased by 40% in the first month.',
    'home.testimonial1.author': 'Alexander V.',
    'home.testimonial1.role': 'CEO TechStartup',
    'home.testimonial2.text': 'We were looking for a premium design for our brand. We got a masterpiece. Very comfortable communication and all deadlines met.',
    'home.testimonial2.author': 'Elena M.',
    'home.testimonial2.role': 'Founder Beauty Studio',
    'home.cta.title1': 'Ready to create',
    'home.cta.title2': 'something outstanding?',
    'home.cta.desc': 'Leave a request, and we will discuss your project, goals, and how design can help your business grow.',
    'home.cta.btn': 'Contact Me',
    
    // Portfolio
    'portfolio.title1': 'My',
    'portfolio.title2': 'Works',
    'portfolio.desc': 'Projects I am proud of. From concept to the final pixel.',
    'portfolio.services1': 'services I provide',
    'portfolio.services2': 'for your business',
    'portfolio.consultation': 'Consultation',
    'portfolio.startProject': 'Start a project',
    'portfolio.hero.desc': 'We are a team of design experts helping businesses grow through visual identity.',
    'portfolio.stats.budget.title': '$60k+',
    'portfolio.stats.budget.desc': 'we manage the advertising budget every month',
    'portfolio.stats.posts.title': '1.3k+',
    'portfolio.stats.posts.desc': 'we create unique posts and creatives every month for growing brands',
    'portfolio.transform.title1': 'we transform',
    'portfolio.transform.title2': 'followers',
    'portfolio.transform.title3': 'into clients',
    'portfolio.transform.desc': 'Our approach is based on analytics, creativity and effective marketing strategies.',
    'portfolio.nextgen.title1': 'we are',
    'portfolio.nextgen.title2': 'next-gen',
    'portfolio.nextgen.title3': 'design company',
    'portfolio.services.uiux.title': 'UI/UX\nDesign',
    'portfolio.services.uiux.desc': 'User research, wireframing, prototyping, and high-fidelity interface design.',
    'portfolio.services.brand.title': 'Brand\nIdentity',
    'portfolio.services.brand.desc': 'Logo design, brand guidelines, typography, and visual language.',
    'portfolio.services.web.title': 'Web\nDevelopment',
    'portfolio.services.web.desc': 'Front-end development, animations, responsive design, and CMS integration.',
    'portfolio.services.motion.title': 'Motion\nGraphics',
    'portfolio.services.motion.desc': '2D/3D animations, promotional videos, and interactive web elements.',
    'portfolio.data.title1': 'data that',
    'portfolio.data.title2': 'proves',
    'portfolio.data.title3': 'our impact',
    'portfolio.data.card1.title': 'Our key results',
    'portfolio.data.card1.desc': 'Targeted design campaigns that reach the right audience at the right time.',
    'portfolio.data.card1.stat1': 'better conversion',
    'portfolio.data.card1.stat2': 'ROI improvement',
    'portfolio.data.card2.title': 'Budget in 2024',
    'portfolio.data.card2.desc': 'Strategically allocated to reach the target audience and drive conversions.',
    'portfolio.data.card3.title': 'Satisfaction',
    'portfolio.data.card3.desc': 'Based on post-project surveys across all our enterprise clients.',
    'portfolio.data.card4.title': 'Projects Delivered',
    'portfolio.data.card4.desc': 'Successfully launched digital products, brands, and marketing campaigns.',
    'portfolio.data.card5.title': 'Global Reach',
    'portfolio.data.card5.desc': 'Working with clients and partners across multiple continents and timezones.',
    'portfolio.data.card6.title': 'Awards Won',
    'portfolio.data.card6.desc': 'Recognized by Awwwards, CSS Design Awards, and other industry leaders.',
    'portfolio.who.title1': 'who our',
    'portfolio.who.title2': 'services',
    'portfolio.who.subtitle': '/ are the perfect\nsolution for',
    'portfolio.who.card1': 'Small and Medium-\nSized Businesses',
    'portfolio.who.card2.desc': 'High-level targeted advertising attracts students and clients seeking professional education or consulting, increasing sign-ups and inquiries.',
    'portfolio.who.card2.title': 'Educational and\nConsulting\nServices',
    'portfolio.who.card3': 'Marketing\nAgencies',
    'portfolio.who.card4': 'E-commerce\nStores',
    'portfolio.who.card5': 'Corporate\nClients',
    'portfolio.who.card6': 'Startups',
    'portfolio.work.title1': 'our work',
    'portfolio.work.title2': 'speaks',
    'portfolio.work.title3': 'for us',
    'portfolio.creatives.title1': 'creatives',
    'portfolio.creatives.title2': 'that',
    'portfolio.creatives.title3': 'work',
    'portfolio.creatives.title4': 'for you',
    
    // Portfolio Projects
    'portfolio.projects.1.title': 'Launch an Instagram account for a beauty studio from scratch.',
    'portfolio.projects.1.desc': '3,100 subscribers in the first 2 weeks, recording for 2 weeks ahead.',
    'portfolio.projects.2.title': 'Rebranding and web design for a local coffee shop.',
    'portfolio.projects.2.desc': 'Increased foot traffic by 40% and online orders by 150%.',
    'portfolio.projects.3.title': 'E-commerce platform for a fashion boutique.',
    'portfolio.projects.3.desc': 'Conversion rate optimization leading to $100k+ monthly revenue.',
    'portfolio.projects.4.title': 'Fitness app UI/UX design and user research.',
    'portfolio.projects.4.desc': '10k+ downloads in the first month with a 4.9 star rating.',
    'portfolio.projects.5.title': 'Corporate identity for a tech startup.',
    'portfolio.projects.5.desc': 'Secured $2M in seed funding with the new pitch deck and branding.',

    // Portfolio Services List
    'portfolio.servicesList.category': 'Service',
    'portfolio.servicesList.1.title': 'Design',
    'portfolio.servicesList.2.title': 'Web Design',
    'portfolio.servicesList.3.title': 'Motion Design',
    'portfolio.servicesList.4.title': 'UI Design',
    'portfolio.servicesList.5.title': 'Corporate Design',
    'portfolio.servicesList.6.title': 'Other',
    
    // Pricing
    'pricing.title1': 'Transparent',
    'pricing.title2': 'Pricing',
    'pricing.desc': 'Choose a suitable format of cooperation. No hidden fees or surprises.',
    'pricing.landing': 'Landing Page',
    'pricing.landing.price': 'from $100',
    'pricing.landing.desc': 'Perfect for product launches, events, or lead generation.',
    'pricing.landing.f1': 'Unique premium design',
    'pricing.landing.f2': 'Responsive layout (React/Tailwind)',
    'pricing.landing.f3': 'Basic animations (Framer Motion)',
    'pricing.landing.f4': 'Lead form integration',
    'pricing.landing.f5': 'Basic SEO optimization',
    'pricing.corp': 'Corporate Website',
    'pricing.corp.price': 'from $150',
    'pricing.corp.desc': 'Multi-page website for a complete company presentation.',
    'pricing.corp.f1': 'Up to 10 unique pages',
    'pricing.corp.f2': 'Complex interactive elements',
    'pricing.corp.f3': 'CMS for content management',
    'pricing.corp.f4': 'Advanced animations',
    'pricing.corp.f5': 'Load speed optimization',
    'pricing.corp.f6': '1 month support',
    'pricing.front': 'Frontend Development',
    'pricing.front.price': '$20/hour',
    'pricing.front.desc': 'Implementation of your ready design on a modern stack.',
    'pricing.front.f1': 'Pixel-perfect layout',
    'pricing.front.f2': 'React / Next.js / Vue',
    'pricing.front.f3': 'Complex WebGL/Canvas effects',
    'pricing.front.f4': 'API integration',
    'pricing.front.f5': 'Legacy code refactoring',
    'pricing.popular': 'Popular Choice',
    'pricing.order': 'Order',
    
    // About
    'about.title1': 'Let\'s get',
    'about.title2': 'acquainted',
    'about.desc1': 'I am a frontend developer and interface designer focusing on premium visual experiences. My goal is not just to write code, but to create a product that evokes emotions and brings profit.',
    'about.desc2': 'In my work, I combine strict engineering logic with a creative approach. I believe that good design should not only be beautiful, but also functional, fast, and accessible.',
    'about.process.title': 'My process',
    'about.process.1.title': 'Briefing and analytics',
    'about.process.1.desc': 'I dive into your business, study the audience and competitors.',
    'about.process.2.title': 'Concept and design',
    'about.process.2.desc': 'I create a visual system, prototypes, and a premium UI.',
    'about.process.3.title': 'Development and animations',
    'about.process.3.desc': 'I do pixel-perfect coding, add smooth motion effects.',
    'about.process.4.title': 'Launch and support',
    'about.process.4.desc': 'I test, optimize, and help with the development of the project.',
    'about.contact.tg': 'Write in Telegram',
    'about.form.title': 'Leave a request',
    'about.form.desc': 'Tell me briefly about your task, and I will contact you within a day to discuss the details.',
    'about.form.nameLabel': 'Your name',
    'about.form.namePlaceholder': 'John Doe',
    'about.form.contactLabel': 'Email or Telegram',
    'about.form.contactPlaceholder': '@username or email@domain.com',
    'about.form.projectLabel': 'About the project',
    'about.form.projectPlaceholder': 'What task are you facing?',
    'about.form.submit': 'Send',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
