import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navbar
    'nav.home': 'Главная',
    'nav.portfolio': 'Портфолио',
    'nav.pricing': 'Конфигуратор',
    'nav.about': 'Обо мне',
    'nav.discuss': 'Обсудить проект',
    
    // Footer
    'footer.desc': 'Премиальная веб-разработка и дизайн.',
    
    // Home
    'home.available': 'Доступен для новых задач',
    'home.title1': 'Создаю сайты, которые',
    'home.title2': 'продают дорого',
    'home.desc': 'От лендингов, что крадут дыхание, до корпоративных систем, которые заставляют конкурентов нервно обновлять страницу.',
    'home.viewWork': 'Креативная витрина',
    'home.services': 'Услуги и цены',
    'home.whyMe': 'Почему выбирают меня',
    'home.quality.title': 'Студийное качество',
    'home.quality.desc': 'Вы получаете уровень топового digital-агентства, работая напрямую без переплат за менеджмент.',
    'home.conversion.title': 'Конверсия в основе',
    'home.conversion.desc': 'Каждый пиксель и анимация работают на удержание внимания и подведение пользователя к целевому действию.',
    'home.stack.title': 'Современный стек',
    'home.stack.desc': 'Использую React, Tailwind, Framer Motion для создания быстрых, плавных и надежных интерфейсов.',
    'home.testimonials': 'Что говорят клиенты',
    'home.testimonial1.text': 'Работа превзошла все ожидания. Сайт выглядит невероятно дорого, анимации плавные, конверсия выросла на 40% в первый месяц.',
    'home.testimonial1.author': 'Александр В.',
    'home.testimonial1.role': 'CEO Recom group',
    'home.testimonial2.text': 'Искали премиальный дизайн для нашего бренда. Получили шедевр. Очень комфортная коммуникация и соблюдение всех сроков.',
    'home.testimonial2.author': 'Елена М.',
    'home.testimonial2.role': 'Основатель Beauty Studio',
    'home.cta.title1': 'Готовы создать',
    'home.cta.title2': 'нечто выдающееся?',
    'home.cta.desc': 'Оставьте заявку, и мы обсудим ваш проект, цели и то, как дизайн может помочь вашему бизнесу расти.',
    'home.cta.btn': 'Обсудить идею',
    
    // Portfolio
    'portfolio.title1': 'Мои',
    'portfolio.title2': 'работы',
    'portfolio.desc': 'Проекты, которыми я горжусь. От концепции до финального пикселя.',
    'portfolio.services1': 'услуги, которые я предоставляю',
    'portfolio.services2': 'для вашего бизнеса',
    'portfolio.consultation': 'Консультация',
    'portfolio.startProject': 'Начать проект',
    'portfolio.hero.desc': 'Я из тех, кто фанатеет от дизайна и искренне хочет, чтобы ваш бизнес выгядел и продавал на голову выше конкурентов',
    'portfolio.stats.budget.title': 'Много- гранный подход',
    'portfolio.stats.budget.desc': 'Photoshop рождает шедевр. After Effects даёт дыхание. AI 2026-го находят уникальность. Vite + React + Tailwind - оживляют в браузере.',
    'portfolio.stats.posts.title': 'Всегда на связи',
    'portfolio.stats.posts.desc': 'создание уникальных постов и креативов каждый месяц для растущих брендов',
    'portfolio.transform.title1': 'превращение',
    'portfolio.transform.title2': 'подписчиков',
    'portfolio.transform.title3': 'в клиентов',
    'portfolio.transform.desc': 'подход основан на аналитике, креативности и эффективных маркетинговых стратегиях.',
    'portfolio.nextgen.title1': 'это',
    'portfolio.nextgen.title2': 'next-gen',
    'portfolio.nextgen.title3': 'дизайн',
    'portfolio.services.uiux.title': 'UI/UX\nДизайн',
    'portfolio.services.uiux.desc': 'Исследования пользователей, вайрфрейминг, прототипирование и дизайн интерфейсов высокой точности.',
    'portfolio.services.brand.title': 'Бренд\nАйдентика',
    'portfolio.services.brand.desc': 'Дизайн логотипов, брендбуки, типографика и визуальный язык.',
    'portfolio.services.web.title': 'Веб\nРазработка',
    'portfolio.services.web.desc': 'Фронтенд-разработка, анимации, адаптивный дизайн и интеграция CMS.',
    'portfolio.services.motion.title': 'Моушн\nДизайн',
    'portfolio.services.motion.desc': '2D/3D анимации, промо-ролики и интерактивные веб-элементы.',
    'portfolio.data.title1': 'данные, которые',
    'portfolio.data.title2': 'доказывают',
    'portfolio.data.title3': 'влияние',
    'portfolio.data.card1.title': 'Ключевые результаты',
    'portfolio.data.card1.desc': 'Целевые дизайн-кампании, которые достигают нужной аудитории в нужное время.',
    'portfolio.data.card1.stat1': 'лучше конверсия',
    'portfolio.data.card1.stat2': 'улучшение ROI',
    'portfolio.data.card2.title': 'Основные усилия направлены',
    'portfolio.data.card2.desc': 'На стратегическое распределение сил и средств для охвата целевой аудитории и стимулирования конверсий.',
    'portfolio.data.card3.title': 'Удовлетворенность',
    'portfolio.data.card3.desc': 'На основе опросов после завершения проектов среди всех наших корпоративных клиентов.',
    'portfolio.data.card4.title': 'Реализовано проектов',
    'portfolio.data.card4.desc': 'Успешно запущенные цифровые продукты, бренды и маркетинговые кампании.',
    'portfolio.data.card5.title': 'Глобальный охват',
    'portfolio.data.card5.desc': 'Открыт для работы с клиентами и партнерами на разных континентах и в разных часовых поясах.',
    'portfolio.data.card6.title': 'Откуда черпаем вдохновение',
    'portfolio.data.card6.desc': 'Awwwards, CSS Design Awards и других лидеров индустрии.',
    'portfolio.who.title1': 'кому важна',
    'portfolio.who.title2': 'моя работа',
    'portfolio.who.subtitle': '/ идеальное решение',
    'portfolio.who.card1': 'Малый и средний бизнес',
    'portfolio.who.card2.desc': 'Высокоуровневая таргетированная реклама привлекает студентов и клиентов, ищущих профессиональное образование или консалтинг, увеличивая количество регистраций и запросов.',
    'portfolio.who.card2.title': 'Образовательные и консалтинговые услуги',
    'portfolio.who.card3': 'Маркетинговые агентства',
    'portfolio.who.card4': 'E-commerce',
    'portfolio.who.card5': 'Корпоративные клиенты',
    'portfolio.who.card6': 'Стартапы',
    'portfolio.work.title1': 'работа',
    'portfolio.work.title2': 'которая',
    'portfolio.work.title3': 'говорит',
    'portfolio.creatives.title1': 'креативы,',
    'portfolio.creatives.title2': 'которые',
    'portfolio.creatives.title3': 'работают',
    'portfolio.creatives.title4': 'на вас',
    
    // Portfolio Projects
    'portfolio.projects.1.title': 'Промышленный корпоративный сайт',
    'portfolio.projects.1.desc': 'Современный лендинг для поставщика промышленного оборудования с акцентом на надёжность, партнёрство и международные поставки.',
    'portfolio.projects.2.title': 'Биотехнологическая платформа',
    'portfolio.projects.2.desc': 'Технологичный лендинг для компании в сфере биотехнологий с визуальным акцентом на инновации, науку и устойчивое развитие.',
    'portfolio.projects.3.title': 'UX/UI дизайн-портфолио',
    'portfolio.projects.3.desc': 'Лендинг для демонстрации интерфейсов и цифровых продуктов с минималистичной эстетикой и современными визуальными эффектами.',
    'portfolio.projects.4.title': 'Кибербезопасность для бизнеса',
    'portfolio.projects.4.desc': 'Футуристичный лендинг для компании по информационной безопасности с акцентом на защиту данных и цифровую инфраструктуру.',
    'portfolio.projects.5.title': 'Цифровая креативная студия',
    'portfolio.projects.5.desc': 'Лендинг агентства цифрового дизайна и разработки с презентацией услуг, проектов и ключевых преимуществ команды.',

    // Portfolio Services List
    'portfolio.servicesList.category': 'Услуга',
    'portfolio.servicesList.1.title': 'Дизайн',
    'portfolio.servicesList.2.title': 'Веб Дизайн',
    'portfolio.servicesList.3.title': 'Моушн Дизайн',
    'portfolio.servicesList.4.title': 'UI Дизайн',
    'portfolio.servicesList.5.title': 'Корпоративный Дизайн',
    'portfolio.servicesList.6.title': 'Другое',
    
    // Pricing
    'pricing.title1': 'Инвестиции в',
    'pricing.title2': 'результат',
    'pricing.desc': 'Прозрачное ценообразование. Вы платите за премиальное качество, соблюдение сроков и внимание к деталям.',
    'pricing.landing': 'Лендинг',
    'pricing.landing.price': 'от ₽10000',
    'pricing.landing.desc': 'Идеально для запуска продукта, мероприятия или сбора лидов.',
    'pricing.landing.f1': 'Уникальный премиум-дизайн',
    'pricing.landing.f2': 'Адаптивная верстка (React/Tailwind)',
    'pricing.landing.f3': 'Базовые анимации (Framer Motion)',
    'pricing.landing.f4': 'Интеграция форм заявки',
    'pricing.landing.f5': 'Базовая SEO-оптимизация',
    'pricing.corp': 'Корпоративный сайт',
    'pricing.corp.price': 'от ₽15000',
    'pricing.corp.desc': 'Многостраничный сайт для полноценного представления компании.',
    'pricing.corp.f1': 'До 10 уникальных страниц',
    'pricing.corp.f2': 'Сложные интерактивные элементы',
    'pricing.corp.f3': 'CMS для управления контентом',
    'pricing.corp.f4': 'Продвинутые анимации',
    'pricing.corp.f5': 'Оптимизация скорости загрузки',
    'pricing.corp.f6': 'Поддержка 1 месяц',
    'pricing.front': 'Frontend Разработка',
    'pricing.front.price': '₽2000/час',
    'pricing.front.desc': 'Реализация вашего готового дизайна на современном стеке.',
    'pricing.front.f1': 'Pixel-perfect верстка',
    'pricing.front.f2': 'React / Next.js / Vue',
    'pricing.front.f3': 'Сложные WebGL/Canvas эффекты',
    'pricing.front.f4': 'Интеграция с API',
    'pricing.front.f5': 'Рефакторинг старого кода',
    'pricing.popular': 'Популярный выбор',
    'pricing.order': 'Заказать',
    'pricing.choose': 'Выбрать тариф',
    
    // Configurator
    'pricing.config.title1': 'Соберите цифровую',
    'pricing.config.title2': 'архитектуру проекта',
    'pricing.config.desc': 'Выбирайте модули и наблюдайте, как формируется ваша конфигурация.',
    'pricing.config.arch': 'Проект архитектура',
    'pricing.config.arch.landing': 'Landing structure',
    'pricing.config.arch.landing.desc': 'Фокусный сайт для запуска продукта или сбора лидов.',
    'pricing.config.arch.multi': 'Multi-page architecture',
    'pricing.config.arch.platform': 'Digital platform core',
    'pricing.config.eng': 'Инженерный арт',
    'pricing.config.eng.react': 'React / Next.js',
    'pricing.config.eng.react.desc': 'Гибкая архитектура с современными технологиями',
    'pricing.config.eng.api': 'API Integrations',
    'pricing.config.mode': 'Project mode',
    'pricing.config.mode.minimal': 'Minimal',
    'pricing.config.mode.balanced': 'Balanced',
    'pricing.config.mode.experimental': 'Experimental',
    'pricing.config.mode.cinematic': 'Cinematic',
    'pricing.config.mode.antiBoring': 'Anti-boring interface mode',
    'pricing.config.visual': 'Визуальная система',
    'pricing.config.visual.nature': 'Nature UI / UX',
    'pricing.config.visual.nature.desc': 'Визуальный акцент на цифровую эстетику',
    'pricing.config.visual.atomic': 'Atomic design system',
    'pricing.config.visual.identity': 'Visual identity layer',
    'pricing.config.motion': 'Motion и сцены',
    'pricing.config.motion.story': 'Motion storytelling',
    'pricing.config.motion.story.desc': 'Плавные анимации и переходы',
    'pricing.config.motion.scroll': 'Interactive scroll scenes',
    'pricing.config.motion.intro': 'Cinematic intro section',
    'pricing.config.motion.3d': '3D device showcase',
    'pricing.config.motion.data': 'Visual data streams',
    'pricing.config.exp': 'Экспериментальные фишки',
    'pricing.config.exp.webgl': 'WebGL visual effects',
    'pricing.config.exp.webgl.desc': 'Anti-boring интерфейс, WebGL',
    'pricing.config.exp.start': 'Start project: Experimental',
    'pricing.config.summary': 'Ваша конфигурация',
    'pricing.config.summary.project': 'Project Summary',
    'pricing.config.summary.profile': 'Project profile',
    'pricing.config.summary.atmosphere': 'Visual Atmosphere',
    'pricing.config.summary.estimated': 'Estimated',
    'pricing.config.summary.avg': 'Средний бюджет проектов: 40,000 - 90,000',
    'pricing.config.summary.btn': 'Запустить проект',

    // About
    'about.title1': 'Давайте',
    'about.title2': 'знакомиться',
    'about.desc1': 'Я frontend-разработчик и дизайнер интерфейсов с фокусом на премиальный визуальный опыт. Моя цель - не просто написать код, а создать продукт, который вызывает эмоции и приносит прибыль.',
    'about.desc2': 'В своей работе я объединяю строгую инженерную логику с креативным подходом. Я верю, что хороший дизайн должен быть не только красивым, но и функциональным, быстрым и доступным.',
    'about.process.title': 'Мой процесс',
    'about.process.1.title': 'Брифинг и аналитика',
    'about.process.1.desc': 'Погружаюсь в ваш бизнес, изучаю аудиторию и конкурентов.',
    'about.process.2.title': 'Концепт и дизайн',
    'about.process.2.desc': 'Создаю визуальную систему, прототипы и премиальный UI.',
    'about.process.3.title': 'Разработка и анимации',
    'about.process.3.desc': 'Верстаю pixel-perfect, добавляю плавные motion-эффекты.',
    'about.process.4.title': 'Запуск и поддержка',
    'about.process.4.desc': 'Тестирую, оптимизирую и помогаю с развитием проекта.',
    'about.contact.tg': 'Написать в Telegram',
    'about.form.title': 'Оставить заявку',
    'about.form.desc': 'Расскажите вкратце о вашей задаче, и я свяжусь с вами в течение дня для обсуждения деталей.',
    'about.form.nameLabel': 'Ваше имя',
    'about.form.namePlaceholder': 'обладатель сайта уровня awwwards',
    'about.form.contactLabel': 'Email или Telegram',
    'about.form.contactPlaceholder': '@username или email@domain.com',
    'about.form.projectLabel': 'О проекте',
    'about.form.projectPlaceholder': 'Какая задача стоит перед вами?',
    'about.form.submit': 'Отправить',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.portfolio': 'Portfolio',
    'nav.pricing': 'Configurator',
    'nav.about': 'About',
    'nav.discuss': 'Discuss the Project',
    
    // Footer
    'footer.desc': 'Premium web development and design.',
    
    // Home
    'home.available': 'Available for new projects',
    'home.title1': 'I create websites that',
    'home.title2': 'sell at a premium',
    'home.desc': 'From landing pages that take your breath away to corporate systems that make competitors nervously refresh the page.',
    'home.viewWork': 'Creative Showcase',
    'home.services': 'Services & Pricing',
    'home.whyMe': 'Why choose me',
    'home.quality.title': 'Studio-Level Quality',
    'home.quality.desc': 'You get the level of a top digital agency while working directly with me, without overpaying for management.',
    'home.conversion.title': 'Conversion at the Core',
    'home.conversion.desc': 'Every pixel and animation works to retain attention and guide the user to the target action.',
    'home.stack.title': 'Modern Stack',
    'home.stack.desc': 'I use React, Tailwind, and Framer Motion to create fast, smooth, and reliable interfaces.',
    'home.testimonials': 'What clients say',
    'home.testimonial1.text': 'The work exceeded all expectations. The site looks incredibly expensive, animations are smooth, conversion increased by 40% in the first month.',
    'home.testimonial1.author': 'Alexander V.',
    'home.testimonial1.role': 'CEO TechStartup',
    'home.testimonial2.text': 'We were looking for a premium design for our brand. We got a masterpiece. Very comfortable communication and all deadlines met.',
    'home.testimonial2.author': 'Elena M.',
    'home.testimonial2.role': 'Founder Beauty Studio',
    'home.cta.title1': 'Ready to create',
    'home.cta.title2': 'something outstanding?',
    'home.cta.desc': 'Leave a request, and we will discuss your project, your goals, and how design can help your business grow.',
    'home.cta.btn': 'Discuss the Idea',
    
    // Portfolio
    'portfolio.title1': 'My',
    'portfolio.title2': 'Work',
    'portfolio.desc': 'Projects I am proud of. From concept to the final pixel.',
    'portfolio.services1': 'services I provide',
    'portfolio.services2': 'for your business',
    'portfolio.consultation': 'Consultation',
    'portfolio.startProject': 'Start a project',
    'portfolio.hero.desc': 'I am one of those people who genuinely live and breathe design and truly want your business to look and sell far above the competition.',
    'portfolio.stats.budget.title': 'A Multi-\nFaceted Approach',
    'portfolio.stats.budget.desc': 'Photoshop creates the masterpiece. After Effects gives it breath. AI tools of 2026 uncover uniqueness. Vite, React, and Tailwind bring it to life in the browser.',
    'portfolio.stats.posts.title': 'Always Within Reach',
    'portfolio.stats.posts.desc': 'Creating unique posts and creatives every month for growing brands.',
    'portfolio.transform.title1': 'turning',
    'portfolio.transform.title2': 'followers',
    'portfolio.transform.title3': 'into clients',
    'portfolio.transform.desc': 'The approach is built on analytics, creativity, and effective marketing strategies.',
    'portfolio.nextgen.title1': 'this is',
    'portfolio.nextgen.title2': 'next-gen',
    'portfolio.nextgen.title3': 'design',
    'portfolio.services.uiux.title': 'UI/UX\nDesign',
    'portfolio.services.uiux.desc': 'User research, wireframing, prototyping, and high-fidelity interface design.',
    'portfolio.services.brand.title': 'Brand\nIdentity',
    'portfolio.services.brand.desc': 'Logo design, brand guidelines, typography, and visual language.',
    'portfolio.services.web.title': 'Web\nDevelopment',
    'portfolio.services.web.desc': 'Front-end development, animations, responsive design, and CMS integration.',
    'portfolio.services.motion.title': 'Motion\nDesign',
    'portfolio.services.motion.desc': '2D/3D animations, promotional videos, and interactive web elements.',
    'portfolio.data.title1': 'data that',
    'portfolio.data.title2': 'proves',
    'portfolio.data.title3': 'impact',
    'portfolio.data.card1.title': 'Key Results',
    'portfolio.data.card1.desc': 'Targeted design campaigns that reach the right audience at the right time.',
    'portfolio.data.card1.stat1': 'better conversion',
    'portfolio.data.card1.stat2': 'improved ROI',
    'portfolio.data.card2.title': 'Core efforts focused on',
    'portfolio.data.card2.desc': 'Strategic allocation of effort and resources to reach the target audience and stimulate conversions.',
    'portfolio.data.card3.title': 'Satisfaction',
    'portfolio.data.card3.desc': 'Based on post-project surveys conducted across all of our corporate clients.',
    'portfolio.data.card4.title': 'Projects delivered',
    'portfolio.data.card4.desc': 'Successfully launched digital products, brands, and marketing campaigns.',
    'portfolio.data.card5.title': 'Global Reach',
    'portfolio.data.card5.desc': 'Open to working with clients and partners across different continents and time zones.',
    'portfolio.data.card6.title': 'Where inspiration comes from',
    'portfolio.data.card6.desc': 'Awwwards, CSS Design Awards, and other leaders of the industry.',
    'portfolio.who.title1': 'who values',
    'portfolio.who.title2': 'my work',
    'portfolio.who.subtitle': '/ the perfect\nsolution',
    'portfolio.who.card1': 'Small and Medium\nBusinesses',
    'portfolio.who.card2.desc': 'High-level targeted advertising attracts students and clients looking for professional education or consulting, increasing registrations and inquiries.',
    'portfolio.who.card2.title': 'Educational and\nConsulting\nServices',
    'portfolio.who.card3': 'Marketing\nAgencies',
    'portfolio.who.card4': 'E-commerce',
    'portfolio.who.card5': 'Corporate\nClients',
    'portfolio.who.card6': 'Startups',
    'portfolio.work.title1': 'work',
    'portfolio.work.title2': 'that',
    'portfolio.work.title3': 'speaks',
    'portfolio.creatives.title1': 'creatives,',
    'portfolio.creatives.title2': 'that',
    'portfolio.creatives.title3': 'work',
    'portfolio.creatives.title4': 'for you',
    
    // Portfolio Projects
    'portfolio.projects.1.title': 'Industrial Corporate Website',
    'portfolio.projects.1.desc': 'A modern landing page for an industrial equipment supplier focusing on reliability, partnership, and international deliveries.',
    'portfolio.projects.2.title': 'Biotech Platform',
    'portfolio.projects.2.desc': 'A tech-forward landing page for a biotechnology company with a visual emphasis on innovation, science, and sustainability.',
    'portfolio.projects.3.title': 'UX/UI Design Portfolio',
    'portfolio.projects.3.desc': 'A landing page showcasing interfaces and digital products with a minimalist aesthetic and modern visual effects.',
    'portfolio.projects.4.title': 'Cybersecurity for Business',
    'portfolio.projects.4.desc': 'A futuristic landing page for an information security company focusing on data protection and digital infrastructure.',
    'portfolio.projects.5.title': 'Digital Creative Studio',
    'portfolio.projects.5.desc': 'A landing page for a digital design and development agency presenting services, projects, and key team advantages.',

    // Portfolio Services List
    'portfolio.servicesList.category': 'Service',
    'portfolio.servicesList.1.title': 'Design',
    'portfolio.servicesList.2.title': 'Web Design',
    'portfolio.servicesList.3.title': 'Motion Design',
    'portfolio.servicesList.4.title': 'UI Design',
    'portfolio.servicesList.5.title': 'Corporate Design',
    'portfolio.servicesList.6.title': 'Other',
    
    // Pricing
    'pricing.title1': 'Investments in',
    'pricing.title2': 'results',
    'pricing.desc': 'Transparent pricing. You pay for premium quality, meeting deadlines, and attention to detail.',
    'pricing.landing': 'Landing Page',
    'pricing.landing.price': 'from RUB 10,000',
    'pricing.landing.desc': 'Perfect for product launches, events, or lead generation.',
    'pricing.landing.f1': 'Unique premium design',
    'pricing.landing.f2': 'Responsive layout (React/Tailwind)',
    'pricing.landing.f3': 'Basic animations (Framer Motion)',
    'pricing.landing.f4': 'Lead form integration',
    'pricing.landing.f5': 'Basic SEO optimization',
    'pricing.corp': 'Corporate Website',
    'pricing.corp.price': 'from RUB 15,000',
    'pricing.corp.desc': 'Multi-page website for a complete company presentation.',
    'pricing.corp.f1': 'Up to 10 unique pages',
    'pricing.corp.f2': 'Complex interactive elements',
    'pricing.corp.f3': 'CMS for content management',
    'pricing.corp.f4': 'Advanced animations',
    'pricing.corp.f5': 'Load speed optimization',
    'pricing.corp.f6': '1 month of support',
    'pricing.front': 'Frontend Development',
    'pricing.front.price': 'RUB 2,000/hour',
    'pricing.front.desc': 'Implementation of your finished design on a modern stack.',
    'pricing.front.f1': 'Pixel-perfect layout',
    'pricing.front.f2': 'React / Next.js / Vue',
    'pricing.front.f3': 'Complex WebGL/Canvas effects',
    'pricing.front.f4': 'API integration',
    'pricing.front.f5': 'Legacy code refactoring',
    'pricing.popular': 'Popular Choice',
    'pricing.order': 'Order',
    'pricing.choose': 'Choose a plan',
    
    // Configurator
    'pricing.config.title1': 'Build your digital',
    'pricing.config.title2': 'project architecture',
    'pricing.config.desc': 'Choose modules and watch your configuration take shape.',
    'pricing.config.arch': 'Project architecture',
    'pricing.config.arch.landing': 'Landing structure',
    'pricing.config.arch.landing.desc': 'Focused site for product launch or lead generation.',
    'pricing.config.arch.multi': 'Multi-page architecture',
    'pricing.config.arch.platform': 'Digital platform core',
    'pricing.config.eng': 'Engineering art',
    'pricing.config.eng.react': 'React / Next.js',
    'pricing.config.eng.react.desc': 'Flexible architecture with modern technologies',
    'pricing.config.eng.api': 'API integrations',
    'pricing.config.mode': 'Project mode',
    'pricing.config.mode.minimal': 'Minimal',
    'pricing.config.mode.balanced': 'Balanced',
    'pricing.config.mode.experimental': 'Experimental',
    'pricing.config.mode.cinematic': 'Cinematic',
    'pricing.config.mode.antiBoring': 'Anti-boring interface mode',
    'pricing.config.visual': 'Visual system',
    'pricing.config.visual.nature': 'Nature UI / UX',
    'pricing.config.visual.nature.desc': 'A visual emphasis on digital aesthetics',
    'pricing.config.visual.atomic': 'Atomic design system',
    'pricing.config.visual.identity': 'Visual identity layer',
    'pricing.config.motion': 'Motion and scenes',
    'pricing.config.motion.story': 'Motion storytelling',
    'pricing.config.motion.story.desc': 'Smooth animations and transitions',
    'pricing.config.motion.scroll': 'Interactive scroll scenes',
    'pricing.config.motion.intro': 'Cinematic intro section',
    'pricing.config.motion.3d': '3D device showcase',
    'pricing.config.motion.data': 'Visual data streams',
    'pricing.config.exp': 'Experimental features',
    'pricing.config.exp.webgl': 'WebGL visual effects',
    'pricing.config.exp.webgl.desc': 'Anti-boring interface, WebGL',
    'pricing.config.exp.start': 'Start project: Experimental',
    'pricing.config.summary': 'Your configuration',
    'pricing.config.summary.project': 'Project Summary',
    'pricing.config.summary.profile': 'Project profile',
    'pricing.config.summary.atmosphere': 'Visual Atmosphere',
    'pricing.config.summary.estimated': 'Estimated',
    'pricing.config.summary.avg': 'Average project budget: RUB 40,000 to 90,000',
    'pricing.config.summary.btn': 'Start project',

    // About
    'about.title1': 'Let\'s',
    'about.title2': 'connect',
    'about.desc1': 'I am a frontend developer and interface designer focusing on premium visual experiences. My goal is not just to write code, but to create a product that evokes emotions and brings profit.',
    'about.desc2': 'In my work, I combine strict engineering logic with a creative approach. I believe that good design should not only be beautiful, but also functional, fast, and accessible.',
    'about.process.title': 'My process',
    'about.process.1.title': 'Briefing and analytics',
    'about.process.1.desc': 'I dive into your business, study the audience and competitors.',
    'about.process.2.title': 'Concept and design',
    'about.process.2.desc': 'I create a visual system, prototypes, and a premium UI.',
    'about.process.3.title': 'Development and animations',
    'about.process.3.desc': 'I build everything pixel-perfect and add smooth motion effects.',
    'about.process.4.title': 'Launch and support',
    'about.process.4.desc': 'I test, optimize, and help the project continue to grow.',
    'about.contact.tg': 'Message me on Telegram',
    'about.form.title': 'Leave a request',
    'about.form.desc': 'Tell me briefly about your task, and I will contact you within a day to discuss the details.',
    'about.form.nameLabel': 'Your name',
    'about.form.namePlaceholder': 'Owner of an Awwwards-level website',
    'about.form.contactLabel': 'Email or Telegram',
    'about.form.contactPlaceholder': '@username or email@domain.com',
    'about.form.projectLabel': 'About the project',
    'about.form.projectPlaceholder': 'What task are you facing?',
    'about.form.submit': 'Send',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
